Modules/Dashboard/Http/routes.php
<?php
Route::group([
    'namespace' => 'Modules\Dashboard\Http\Controllers',
    'as' => 'dashboard.'
], function ($r) {

    $r->get('/', 'DashboardController@index')->name('index');

});

Modules/Dashboard/Http/Controllers/DashboardController.php
<?php

namespace Modules\Dashboard\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Route;
use Modules\Purchase\Entities\Purchase;

class DashboardController extends Controller
{

    public function index(Purchase $purchase)
    {
        $purchases = $purchase->orderBy('created_at', 'desc')
            ->limit(5)
            ->get();
        return view('dashboard::index', compact('purchases'));
    }

    public function create()
    {
        return view('dashboard::create');
    }

    public function store(Request $request)
    {
    }

    public function show()
    {
        return view('dashboard::show');
    }

    public function edit()
    {
        return view('dashboard::edit');
    }

    public function update(Request $request)
    {
    }

    public function destroy()
    {
    }
}

Modules/Dashboard/Resources/views/layouts/elements/alerts.blade.php
@if (isset($errors))
    <div class="row">
        @if (session()->has('success'))
            <div class="alert alert-success">
                {!! session('success') !!}
            </div>
        @endif
        @if (session()->has('info'))
            <div class="alert alert-info">
                {!! session('info') !!}
            </div>
        @endif
        @if (session()->has('warning'))
            <div class="alert alert-warning">
                {!! session('warning') !!}
            </div>
        @endif
        @if (session()->has('error'))
            <div class="alert alert-danger">
                {!! session('error') !!}
            </div>
        @endif
        @if ($errors->count() > 0)
            <div class="alert alert-danger">
                <strong>Verifique os campos em destaques.</strong>
            </div>
        @endif
    </div>
@endif

Modules/Dashboard/Resources/views/layouts/elements/footer.blade.php
<div class="footer">
    <div class="pull-right">
        10GB of <strong>250GB</strong> Free.
    </div>
    <div>
        {!! setting('sistema.direitos') !!}
    </div>
</div>

Modules/Dashboard/Resources/views/layouts/elements/menu.blade.php
<div class="navbar-collapse collapse" id="navbar">
    <ul class="nav navbar-nav">
        <li class="dropdown">
            <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown"> Clientes / Usuários <span class="caret"></span></a>
            <ul role="menu" class="dropdown-menu">
                <li>
                    <a href="{!! route('user.index') !!}">Usuários</a>
                </li>
                <li>
                    <a href="{!! route('notification.index') !!}">Notificações</a>
                </li>
                <li>
                    <a href="{!! route('lead.index') !!}">Lead / Contatos</a>
                </li>
                <li>
                    <a href="{!! route('common_question.index') !!}">Perguntas Frequentes</a>
                </li>
            </ul>
        </li>
        <li class="dropdown">
            <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown"> E-Cursos <span class="caret"></span></a>
            <ul role="menu" class="dropdown-menu">
                <li>
                    <a href="{!! route('course.index') !!}">Cursos</a>
                </li>
                <li>
                    <a href="{!! route('team.index') !!}">Turmas</a>
                </li>
                <li>
                    <a href="{!! route('lesson.index') !!}">Aulas</a>
                </li>
                <li>
                    <a href="{!! route('content.index') !!}">Conteúdos</a>
                </li>
                <li>
                    <a href="{!! route('course.showcase.index') !!}">Vitrines</a>
                </li>
            </ul>
        </li>
        <li class="dropdown">
            <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown"> Blog <span class="caret"></span></a>
            <ul role="menu" class="dropdown-menu">
                <li>
                    <a href="{!! route('blog.index') !!}">Posts</a>
                </li>
                <li>
                    <a href="{!! route('post_category.index') !!}">Categorias</a>
                </li>
            </ul>
        </li>
        <li class="dropdown">
            <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown"> Complementos <span class="caret"></span></a>
            <ul role="menu" class="dropdown-menu">
                <li>
                    <a href="{!! route('banner.index') !!}">Banners</a>
                </li>
            </ul>
        </li>
        <li class="dropdown">
            <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown"> Pedidos <span class="caret"></span></a>
            <ul role="menu" class="dropdown-menu">
                <li>
                    <a href="{!! route('purchase.index') !!}">Ordem de compras</a>
                </li>
            </ul>
        </li>
    </ul>
    <ul class="nav navbar-top-links navbar-right">
        <li>
            <a href="{!! route('auth.logout') !!}">
                <i class="fa fa-sign-out"></i> Sair
            </a>
        </li>
    </ul>
</div>

Modules/Dashboard/Resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="{!! config()->get('lang') !!}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>@yield('title') | {!! setting('nome') !!}</title>

    {!! Html::style('assets/vendors/bootstrap/bootstrap.min.css') !!}
    {!! Html::style('assets/vendors/sweetalert/sweetalert.min.css') !!}
    {!! Html::style('assets/vendors/animate/animate.css') !!}

    {!! Html::style('assets/vendors/redactor/redactor.min.css') !!}

    {!! Html::style('assets/vendors/bootstrap-datepicker/bootstrap-datepicker.min.css') !!}

    {!! Html::style('assets/vendors/jquery-tag/jquery-ui.css') !!}
    {!! Html::style('assets/vendors/jquery-tag/jquery.tagit.css') !!}

    {!! Html::style('assets/vendors/toastr/toastr.min.css') !!}
    @yield('css')
    {!! Html::style(Module::asset('dashboard:css/main.css')) !!}
    {!! Html::style('assets/vendors/inspina/style.css') !!}

    {!! Html::script('assets/vendors/pusher/pusher.min.js') !!}

    {!! Html::style('assets/vendors/ionRangeSlider/ion.rangeSlider.css') !!}
    {!! Html::style('assets/vendors/ionRangeSlider/ion.rangeSlider.skinNice.css') !!}

    <script>
        var APP_URL = '{!! url('/') !!}/',
            CMS_URL = APP_URL + '{!! env('SYSTEM_CMS_PREFIX') !!}/',
            USER_TOKEN = '{!! auth()->user()->token !!}';

        // Enable pusher logging - don't include this in production
        //        Pusher.logToConsole = true;

        var pusher = new Pusher('{!! env('PUSHER_APP_KEY') !!}', {
            cluster: '{!! env('PUSHER_CLUSTER') !!}',
            encrypted: true
        });
    </script>
</head>

<body class="top-navigation">

<div id="wrapper">

    <div id="page-wrapper" class="gray-bg">
        <div class="row border-bottom white-bg">
            <nav class="navbar navbar-static-top" role="navigation">

                <div class="navbar-header">
                    <button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse"
                            class="navbar-toggle collapsed" type="button">
                        <i class="fa fa-reorder"></i>
                    </button>
                    <a href="{!! route('dashboard.index') !!}" class="navbar-brand">{!! setting('nome') !!}</a>
                </div>

                @include('dashboard::layouts.elements.menu')

            </nav>
        </div>

        <div class="wrapper wrapper-content">
            <div class="container">

                @include('dashboard::layouts.elements.alerts')

                @yield('content')
            </div>
        </div>

        <div class="clearfix"></div>

        @include('dashboard::layouts.elements.footer')


        {{--<div class="floating-modal">--}}
        {{--@yield("right-modal")--}}
        {{--</div>--}}

    </div>

</div>

{!! Html::script('assets/vendors/jquery/jquery-2.1.1.js') !!}
{!! Html::script('assets/vendors/jquery/jquery-ui.min.js') !!}

{!! Html::script('assets/vendors/font-awesome/5.0.6.js') !!}

{!! Html::script('assets/vendors/bootstrap/bootstrap.min.js') !!}
{!! Html::script('assets/vendors/metis-menu/jquery.metisMenu.js') !!}
{!! Html::script('assets/vendors/slim-scroll/jquery.slimscroll.min.js') !!}
{!! Html::script('assets/vendors/sweetalert/sweetalert.min.js') !!}

{!! Html::script('assets/vendors/bootstrap-datepicker/bootstrap-datepicker.min.js') !!}
{!! Html::script('assets/vendors/bootstrap-datepicker/bootstrap-datepicker.pt-BR.min.js') !!}

{!! Html::script('assets/vendors/redactor/redactor.min.js') !!}

{!! Html::script('assets/vendors/jquery-tag/tag-it.min.js') !!}

{!! Html::script('assets/vendors/toastr/toastr.min.js') !!}
{!! Html::script('assets/vendors/pace/pace.min.js') !!}
{!! Html::script('assets/vendors/inspina/inspina.js') !!}
{!! Html::script('assets/vendors/ionRangeSlider/ion.rangeSlider.min.js') !!}

{!! Html::script('assets/vendors/axios/axios.js') !!}
{!! Html::script('assets/vendors/vue/vue.js') !!}
{!! Html::script('assets/vendors/vue-mask/vue-mask.min.js') !!}
{!! Html::script(Module::asset('purchase:js/vendors/vue-mask-money/vue-mask-money.js')) !!}

@yield('script')

{!! Html::script(Module::asset('dashboard:js/main.js')) !!}

@yield('main-js')

<script type="text/javascript">
    Vue.use(VueTheMask);
    Vue.use(VMoney);
    new Vue({
        el: '#wrapper',
        data: function () {
            return {
                // Variável para poder acessar dados externos dos componentes
                // Pra criar um padrão, utilize o nome do módulo em camelCase
                global: {
                    teamModules: {
                        module_id: ""
                    }
                }
            }
        }
    });

    var user_channel = pusher.subscribe(USER_TOKEN);
    user_channel.bind('notification', function (data) {
        toastr.success(data.message);
    });

    var private_channel = pusher.subscribe('private01');
    private_channel.bind('notification', function (data) {
        toastr.info(data.message);
    });

    var channel = pusher.subscribe('purchases');
    channel.bind('alert', function (data) {
        toastr.success(data.message);
    });
    channel.bind('{!! auth()->user()->token !!}', function (data) {
        console.log(data);
        toastr.success(data.message);
    });
</script>


</body>
</html>