Modules/Blog/Http/routes.php
<?php

Route::group([
    'prefix' => 'blog',
    'as' => 'blog.',
    'namespace' => 'Modules\Blog\Http\Controllers'
], function ($r) {

    $r->get('/', 'BlogController@index')->name('index');

    $r->get('criar', 'BlogController@create')->name('create');
    $r->post('criar', 'BlogController@store')->name('store');


    $r->get('{id}/editar', 'BlogController@edit')->name('edit');
    $r->patch('{id}/editar', 'BlogController@update')->name('update');

    $r->delete('{id}/deletar', 'BlogController@destroy')->name('destroy');
});

Route::group([
    'prefix' => 'categorias',
    'as' => 'post_category.',
    'namespace' => 'Modules\Blog\Http\Controllers'
], function ($r) {

    $r->get('/', 'PostCategoryController@index')->name('index');

    $r->get('criar', 'PostCategoryController@create')->name('create');
    $r->post('criar', 'PostCategoryController@store')->name('store');

    $r->get('{id}/editar', 'PostCategoryController@edit')->name('edit');
    $r->patch('{id}/editar', 'PostCategoryController@update')->name('update');

    $r->delete('{id}/deletar', 'PostCategoryController@destroy')->name('destroy');

});

Modules/Blog/Resources/views/create.blade.php
@extends('dashboard::layouts.master')

@section('title', 'Novo Post')

@section('content')
    <div class="row">
        {!! Form::open(['route' => 'blog.store', 'files' => true]) !!}
        <div class="ibox float-e-margins">

            <div class="ibox-title">
                <h5>Novo Post</h5>
            </div>

            <div class="ibox-content">

                <div class="row">
                    <div class="col-sm-4">
                        <a href="{!! route('blog.index') !!}" class="btn btn-outline btn-warning">
                            <i class="fa fa-arrow-left"></i> Listar todas as postagens
                        </a>
                    </div>
                </div>

                <hr>


                @include('blog::form')
            </div>
        </div>
        {!! Form::close() !!}
    </div>
@stop

Modules/Blog/Resources/views/edit.blade.php
@extends('dashboard::layouts.master')

@section('title', 'Editar Post')

@section('content')
    <div class="row">
        {!! Form::model($edit, ['route' => ['blog.update', $edit->id], 'files' => true, 'method' => 'PATCH']) !!}
        <div class="ibox float-e-margins">

            <div class="ibox-title">
                <h5>Post - <strong class="text-success">{!! $edit->name !!}</strong></h5>
            </div>

            <div class="ibox-content">

                <div class="row">
                    <div class="col-sm-4">
                        <a href="{!! route('blog.index') !!}" class="btn btn-outline btn-warning">
                            <i class="fa fa-arrow-left"></i> Listar todas as postagens
                        </a>
                    </div>
                </div>

                <hr>

                @include('blog::form')
            </div>
        </div>
        {!! Form::close() !!}
    </div>
@stop

Modules/Blog/Resources/views/form.blade.php
<div class="row">

    <image-preview inline-template>
        <div class="col-lg-12">
            <div class="form-group">
                @if (isset($edit) && $edit->banner_image != "")
                    <img src="{!! $edit->banner_image !!}" id="preview-image" class="img-responsive" v-if="!image" />
                    <img v-bind:src="image" id="preview-image" class="img-responsive" />
                @else
                    <img v-bind:src="image" id="preview-image" class="img-responsive" />
                @endif
            </div>
            <div class="form-group">
                <div class="form-group{!! $errors->first('image') ? ' has-error' : '' !!}">
                    <label for="image">
                        Imagem Banner ({!! config('blog.banner_width') !!}w x {!! config('blog.banner_height') !!}h) <label class="badge badge-info">Opcional</label>
                    </label>
                    {!! Form::file('image', ['class' => 'form-control', 'placeholder' => 'Imagem', 'v-on:change' => 'preview']) !!}
                    {!! $errors->first('image', '<span class="help-block">:message</span>') !!}
                </div>
            </div>
            <hr>
        </div>
    </image-preview>

    {{--<image-preview inline-template>--}}
        {{--<div class="col-lg-12">--}}
            {{--<div class="row">--}}
                {{--<div class="col-lg-6">--}}
                    {{--<div class="form-group">--}}
                        {{--<img v-bind:src="image" id="preview-image" class="img-responsive" />--}}
                    {{--</div>--}}
                    {{--<div class="form-group{!! $errors->first('thumb') ? ' has-error' : '' !!}">--}}
                        {{--<label for="thumb">--}}
                            {{--Thumb ({!! config('blog.thumb_width') !!}w x {!! config('blog.thumb_height') !!}h) <label class="badge badge-info">Opcional</label>--}}
                        {{--</label>--}}
                        {{--{!! Form::file('thumb', ['class' => 'form-control', 'placeholder' => 'Thumb', 'v-on:change' => 'preview']) !!}--}}
                        {{--{!! $errors->first('thumb', '<span class="help-block">:message</span>') !!}--}}
                    {{--</div>--}}
                {{--</div>--}}
            {{--</div>--}}
            {{--<hr>--}}
        {{--</div>--}}
    {{--</image-preview>--}}

    <div class="col-lg-12">

        <div class="row">
            <div class="col-lg-6">
                <div class="form-group">
                    <label class="clear">
                        Status <label class="badge badge-danger">Obrigatório</label>
                    </label>
                    <label class="radio-inline">
                        {!! Form::radio('status', 1, true) !!} Ativo
                    </label>
                    <label class="radio-inline">
                        {!! Form::radio('status', 0, false) !!} Inativo
                    </label>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-6">
                <div class="form-group{!! $errors->first('name') ? ' has-error' : '' !!}">
                    <label for="name">
                        Título <label class="badge badge-danger">Obrigatório</label>
                    </label>
                    {!! Form::text('name', null, ['class' => 'form-control', 'id' => 'slug', 'placeholder' => 'Título']) !!}
                    {!! $errors->first('name', '<span class="help-block">:message</span>') !!}
                </div>
            </div>
            <div class="col-lg-6">
                <div class="form-group{!! $errors->first('slug') ? ' has-error' : '' !!}">
                    <label for="slug">
                        URl <label class="badge badge-danger">Obrigatório</label>
                    </label>
                    <div class="input-group">
                        <span class="input-group-addon">{!! url('/') !!}/</span>
                        {!! Form::text('slug', null, ['class' => 'form-control', 'placeholder' => 'URl', 'id' => 'slug-target']) !!}
                    </div>
                    {!! $errors->first('slug', '<span class="help-block">:message</span>') !!}
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-6">
                <div class="form-group{!! $errors->first('category_id') ? ' has-error' : '' !!}">
                    <label for="category_id">
                        Categoria <label class="badge badge-info">Opcional</label>
                    </label>
                    {!! Form::select('category_id', $postCategories, null, ['class' => 'form-control', 'placeholder' => 'Categoria']) !!}
                    {!! $errors->first('category_id', '<span class="help-block">:message</span>') !!}
                </div>
            </div>
        </div>
        
        <div class="form-group{!! $errors->first('video') ? ' has-error' : '' !!}">
            <label for="video">
                Vídeo <label class="badge badge-info">Opcional</label>
            </label>
            {!! Form::text('video', null, ['class' => 'form-control', 'placeholder' => 'Vídeo']) !!}
            {!! $errors->first('video', '<span class="text-danger">:message</span>') !!}
        </div>
        

        <div class="form-group{!! $errors->first('text') ? ' has-error' : '' !!}">
            <label for="text">
                Conteúdo <label class="badge badge-info">Opcional</label>
            </label>
            {!! Form::textarea('text', null, ['class' => 'form-control redactor-editor', 'placeholder' => 'Digite aqui o conteúdo da postagem.']) !!}
            {!! $errors->first('text', '<span class="text-danger">:message</span>') !!}
        </div>
    </div>

</div>

<div class="row">
    <div class="col-lg-6 col-sm-6">
        <button type="submit" class="btn btn-primary">
            <i class="fa fa-check"></i> Salvar Post
        </button>
    </div>
</div>

@section('script')
    {!! Html::script(Module::asset('blog:js/crud.js')) !!}
    {!! Html::script('assets/js/components/image-preview.js') !!}
@endsection

Modules/Blog/Resources/views/index.blade.php
@extends('dashboard::layouts.master')

@section('title', 'Blog')

@section('content')
    <div class="row">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Blog - <strong class="text-success">Posts</strong></h5>
            </div>
            <div class="ibox-content">

                <div class="row">
                    <div class="col-sm-12">
                        <a href="{!! route('blog.create') !!}" class="btn btn-outline btn-success">
                            <i class="fa fa-plus"></i> Cadastrar Posts
                        </a>
                        <a href="{!! request()->fullUrl() !!}" class="btn btn-outline btn-default">
                            <i class="fa fa-repeat"></i> Atualizar
                        </a>
                    </div>
                </div>

                <hr>

                <div class="row">

                    <div class="col-lg-12">
                        <table class="table table-responsive table-bordered table-stripped">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Nome</th>
                                <th>URl</th>
                                <th>Status</th>
                                <th width="15%">Opções</th>
                            </tr>
                            </thead>
                            <tbody>
                            @if ($data->count())
                                @foreach($data as $row)
                                    <tr>
                                        <td>{!! $row->id !!}</td>
                                        <td>{!! $row->name !!}</td>
                                        <td>{!! url("/{$row->slug}") !!}</td>
                                        <td>{!! $row->statusLabel !!}</td>
                                        <td>
                                            {!! Form::open(['route' => ['blog.destroy', $row->id], 'method' => 'DELETE', 'onsubmit' => 'beforeConfirm(this, event)']) !!}
                                            <a href="{!! route('blog.edit', $row->id) !!}" class="btn btn-outline btn-info btn-xs">
                                                <i class="fa fa-pencil"></i> Editar
                                            </a>
                                            <button class="btn btn-outline btn-danger btn-xs" type="submit">
                                                <i class="fa fa-trash"></i> Deletar
                                            </button>
                                            {!! Form::close() !!}
                                        </td>
                                    </tr>
                                @endforeach
                            @else
                                <tr>
                                    <td colspan="5">Nenhum post no momento, <a href="{!! route('blog.create') !!}">clique aqui</a> adicione um post</td>
                                </tr>
                            @endif
                            </tbody>
                        </table>
                    </div>

                </div>

            </div>
        </div>
    </div>
@stop