Modules/Sac/Http/routes.php
<?php

Route::group([
    'prefix' => 'leads',
    'as' => 'lead.',
    'namespace' => 'Modules\Sac\Http\Controllers'
], function ($r) {

    $r->get('/', 'SacController@index')->name('index');
    $r->get('{id}/visualizar', 'SacController@show')->name('show');

    $r->post('{id}/adicionar/observacao', 'SacController@addObservation')->name('add_observation');
    $r->post('{id}/alterar/status', 'SacController@changeStatus')->name('change_status');

});


Route::group([
    'prefix' => 'pergunta-frequente',
    'as' => 'common_question.',
    'namespace' => 'Modules\Sac\Http\Controllers'
], function ($r) {

    $r->get('/', 'CommonQuestionController@index')->name('index');

    $r->get('criar', 'CommonQuestionController@create')->name('create');
    $r->post('criar', 'CommonQuestionController@store')->name('store');


    $r->get('{id}/editar', 'CommonQuestionController@edit')->name('edit');
    $r->patch('{id}/editar', 'CommonQuestionController@update')->name('update');

    $r->delete('{id}/deletar', 'CommonQuestionController@destroy')->name('destroy');

});

Modules/Sac/Entities/Lead.php
<?php

namespace Modules\Sac\Entities;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Lead extends Model
{

    use SoftDeletes;

    protected $fillable = ["lead_category_id", "parent_id", "name", "email", "status", "error"];

    protected $appends = ['status_reason'];

    /**
     * @return mixed
     * Converte a data que está vindo do pedido para d/m/Y
     */
    public function getCreatedAttribute()
    {
        if ($this->created_at != '') {
            return $this->created_at->format('d/m/Y H:i:s');
        }
    }

    /**
     * @return string
     *
     * Retorna o status do leads com label
     */
    public function getStatusReasonAttribute()
    {
        switch ($this->status) {
            case 0:
                return '<label class="badge badge-danger">Aguardando resposta</label>';
                break;
            case 1:
                return '<label class="badge badge-success">Finalizado</label>';
                break;
            default:
                return '<label class="badge badge-danger">Aguardando resposta</label>';
                break;
        }
    }

    public function LeadParents()
    {
        return $this->hasMany(Lead::class, 'parent_id');
    }

    public function LeadCategory()
    {
        return $this->belongsTo(LeadCategory::class, 'lead_category_id')->withDefault();
    }

    public function LeadFormData()
    {
        return $this->hasOne(LeadFormData::class, 'lead_id')->orderBy('created_at', 'desc');
    }

    public function LeadFormDatas()
    {
        return $this->hasMany(LeadFormData::class, 'lead_id')->orderBy('value');
    }

    public function LeadObservation()
    {
        return $this->hasOne(LeadObservation::class, 'lead_id')->orderByDesc('created_at');
    }

    public function LeadObservations()
    {
        return $this->hasMany(LeadObservation::class, 'lead_id');
    }
}

Modules/Sac/Resources/views/index.blade.php
@extends('dashboard::layouts.master')

@section('title', 'Leads, Contato')

@section('content')
    <div class="row">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Leads, Contato</h5>
            </div>
            <div class="ibox-content">

                <div class="row">
                    <div class="col-sm-12">
                        @if (request()->has("status"))
                            <a href="{!! route('lead.index') !!}" class="btn btn-outline btn-warning">
                                Listar todos os Leads <i class="fas fa-arrow-left"></i>
                            </a>
                        @endif
                        @if ($wait_count > 0)
                            <a href="{!! route('lead.index', ['status' => 0]) !!}" class="btn btn-danger">
                                Aguardando resposta <label class="badge badge-inverse">{!! $wait_count !!}</label>
                            </a>
                        @endif
                        <a href="{!! route('common_question.index') !!}" class="btn btn-outline btn-success">
                            <i class="fas fa-question-circle"></i> Pergunta Frequente
                        </a>
                        <a href="{!! request()->fullUrl() !!}" class="btn btn-outline btn-default">
                            <i class="fa fa-repeat"></i> Atualizar
                        </a>
                    </div>
                </div>

                <hr>

                <div class="row">
                    <div class="col-lg-12">
                        <table class="table table-responsive table-bordered">
                            <thead>
                            <tr>
                                <td>#Lead</td>
                                <td>Nome</td>
                                <td>E-mail</td>
                                <td>Categoria</td>
                                <td>Status</td>
                                <td>Data/Hora</td>
                                <td>Ações</td>
                            </tr>
                            </thead>
                            <tbody>
                            @if ($leads->count())
                                @foreach($leads as $lead)
                                    <tr>
                                        <td>{!! $lead->id !!}</td>
                                        <td>{!! $lead->name !!}</td>
                                        <td>{!! $lead->email !!}</td>
                                        <td>{!! $lead->LeadCategory->name !!}</td>
                                        <td>{!! $lead->status_reason !!}</td>
                                        <td>{!! $lead->created !!}</td>
                                        <td>
                                            <a href="{!! route('lead.show', $lead->id) !!}" class="btn btn-xs btn-outline btn-success">
                                                <i class="fa fa-eye"></i> Visualizar
                                            </a>
                                        </td>
                                    </tr>
                                @endforeach
                            @else
                                <tr>
                                    <td colspan="7">Nenhum registro no momento.</td>
                                </tr>
                            @endif
                            </tbody>
                        </table>
                    </div>
                </div>

            </div>
        </div>
    </div>
@stop

Modules/Sac/Resources/views/show.blade.php
@extends('dashboard::layouts.master')

@section('title', 'Lead #' . $lead->id)

@section('content')
    <div class="row">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Lead #{!! $lead->id !!}</h5>
            </div>
            <div class="ibox-content">

                <div class="row">
                    <div class="col-sm-4">
                        <a href="{!! route('lead.index') !!}" class="btn btn-outline btn-warning">
                            <i class="fa fa-arrow-left"></i> Listar todos os contatos
                        </a>
                    </div>
                </div>
                <hr>
                <div class="row">

                    <div class="col-lg-12">
                        @if ($lead->LeadObservations->count())
                            @php
                            $observation = $lead->LeadObservation;
                            @endphp
                            <div class="alert alert-success">
                                <strong>Última observação - {!! $lead->created !!}</strong>
                                <p>{!! $observation->text !!}</p>
                            </div>
                        @endif
                    </div>

                    <div class="col-lg-6">
                        <h3 class="forum-title bg-primary">
                            Dados principais
                        </h3>
                        <p>
                            <strong>Nome:</strong> {!! $lead->name !!} <br>
                            <strong>E-mail:</strong> {!! $lead->email !!}
                        </p>

                        @if ($lead->parent_id == 0)
                            <h3 class="forum-title bg-primary">
                                Status deste contato
                            </h3>

                            {!! Form::model($lead, ['route' => ['lead.change_status', $lead->id]]) !!}
                            <div class="form-group{!! $errors->first('status') ? ' has-error' : '' !!}">
                                <div class="input-group">
                                    {!! Form::select('status', [0 => 'Aguardando resposta', 1 => 'Finalizado'], null, ['class' => 'form-control', 'required', 'placeholder' => 'Selecione o novo status']) !!}
                                    {!! $errors->first('status', '<span class="text-danger">:message</span>') !!}
                                    <span class="input-group-btn">
                                        <button class="btn btn-primary" type="submit"><i class="fa fa-check"></i> Alterar
                                            status
                                        </button>
                                    </span>
                                </div>
                            </div>
                            {!! Form::close() !!}
                        @endif
                    </div>

                    <div class="col-lg-6">
                        <h3 class="forum-title bg-primary">
                            Dados do formulário
                        </h3>
                        @if ($lead->LeadFormDatas->count())
                            <p>
                                @foreach($lead->LeadFormDatas as $formData)
                                    <strong>{!! $formData->name !!}:</strong> {!! $formData->value !!}<br>
                                @endforeach
                            </p>
                        @else
                            <p>
                                Apenas os dados principais foram preenchidos.
                            </p>
                        @endif
                    </div>


                    <div class="col-lg-12">
                        <hr>
                    </div>
                </div>

                @if ($lead->parent_id == 0 && false)
                    <div class="row">
                        <div class="col-lg-12">
                            <h3 class="forum-title bg-danger">
                                Tentativas
                            </h3>
                            <table class="table table-responsive table-bordered table-striped">
                                <thead>
                                <tr>
                                    <td>#Lead</td>
                                    <td>Campos preenchidos</td>
                                    <td>Observação</td>
                                    <td>Data/Hora</td>
                                    <td>Ações</td>
                                </tr>
                                </thead>
                                <tbody>
                                @if ($lead->LeadParents->count())
                                    @foreach($lead->LeadParents as $parent)
                                        <tr>
                                            <td>{!! $parent->id !!}</td>
                                            <td>{!! str_limit($parent->LeadFormDatas->pluck('value', 'name'), 30) !!}</td>
                                            <td>{!! str_limit($parent->LeadObservation->text, 30) !!}</td>
                                            <td>{!! $parent->created !!}</td>
                                            <td>
                                                <a href="{!! route('lead.show', $parent->id) !!}" class="btn btn-xs btn-outline btn-success">
                                                    <i class="fa fa-eye"></i> Visualizar
                                                </a>
                                            </td>
                                        </tr>
                                    @endforeach
                                @else
                                    <tr>
                                        <td colspan="7">Nenhum registro no momento.</td>
                                    </tr>
                                @endif
                                </tbody>
                            </table>
                        </div>
                    </div>
                @endif

                <div class="row">
                    {!! Form::open(['route' => ['lead.add_observation', $lead->id]]) !!}
                    <div class="col-lg-12">
                        <div class="form-group{!! $errors->first('text') ? ' has-error' : '' !!}">
                            <label for="text">
                                Observação <label class="badge badge-info">Opcional</label>
                            </label>
                            {!! Form::textarea('text', null, ['class' => 'form-control', 'rows' => 2, 'required', 'placeholder' => 'Observação', 'style' => 'resize: none']) !!}
                            {!! $errors->first('text', '<span class="text-danger">:message</span>') !!}
                        </div>
                        <button type="submit" class="btn btn-primary">
                            <i class="fa fa-check"></i> Salvar observação
                        </button>
                    </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@stop